/* USER ?Éù?Ñ± (Í¥?Î¶¨Ïûê Í≥ÑÏ†ï?úºÎ°? ?ã§?ñâ) */

--CREATE USER CODETREE IDENTIFIED BY CODETREE;
--GRANT CONNECT, RESOURCE TO CODETREE;

/* CODETREE Í≥ÑÏ†ï?úºÎ°? ?ã§?ñâ */
DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE ADDRESS;

DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_BNO;


/* Member */
CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(15) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    GENDER  VARCHAR2(3),
    BIRTHDAY    DATE,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN MEMBER.USER_ID IS '?öå?õê ?ïÑ?ù¥?îî';
COMMENT ON COLUMN MEMBER.USER_PWD IS '?öå?õê ÎπÑÎ?Î≤àÌò∏';
COMMENT ON COLUMN MEMBER.USER_NAME IS '?öå?õêÎ™?';
COMMENT ON COLUMN MEMBER.GENDER IS '?Ñ±Î≥?(?Ç®/?ó¨/NULL)';
COMMENT ON COLUMN MEMBER.BIRTHDAY IS '?Éù?ÖÑ?õî?ùº';
COMMENT ON COLUMN MEMBER.PHONE IS '?†Ñ?ôîÎ≤àÌò∏';
COMMENT ON COLUMN MEMBER.EMAIL IS '?ù¥Î©îÏùº';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '?öå?õêÍ∞??ûÖ?ùº';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '?†ïÎ≥¥Ïàò?†ï?ùº';
COMMENT ON COLUMN MEMBER.STATUS IS '?öå?õê ?ÉÅ?Éú(Y/N)';

CREATE SEQUENCE SEQ_UNO
NOCACHE;

INSERT INTO MEMBER
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', 'Í¥?Î¶¨Ïûê', NULL, '1999-10-31', '010-1111-2222', 'admin@cd.or.kr', '2022-02-10', '2022-02-10', 'Y');

INSERT INTO MEMBER
VALUES (SEQ_UNO.NEXTVAL, 'user1', '1234', '?ôçÍ∏∏Îèô', '?Ç®', '1999-10-31', '010-1131-1978', 'gildong@cd.or.kr', '2023-02-10', '2023-02-10', 'Y');

INSERT INTO MEMBER
VALUES (SEQ_UNO.NEXTVAL, 'user2', '1234', 'ÏΩ©Ï•ê', '?ó¨', '1999-10-31', NULL, 'congcong@cd.or.kr', '2024-10-02', '2024-10-02', 'Y');


/* Board */
CREATE TABLE BOARD (
    BOARD_NO      NUMBER         PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100)    NOT NULL,
    BOARD_TYPE  VARCHAR(10) NOT NULL,
    BOARD_CATEGORY  VARCHAR2(15),
    BOARD_CONTENT   VARCHAR(500)    NOT NULL,
    PROD_IMG    VARCHAR(300),
    PRICE   INT NOT NULL,
    BID_PRICE   INT,
    STOCK   INT NOT NULL,
    SELLER_NO  int,
    REGISTER_DATE DATE    DEFAULT SYSDATE,
    STATUS  CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN BOARD.BOARD_NO IS 'Í≤åÏãúÍ∏? Î≤àÌò∏';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS 'Í≤åÏãúÍ∏? ?†úÎ™?';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '?åêÎß? ???ûÖ(Í≤ΩÎß§/Ï§ëÍ≥†Í±∞Îûò)';
COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS 'Í≤åÏãúÍ∏? Ïπ¥ÌÖåÍ≥†Î¶¨';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS 'Í≤åÏãúÍ∏? ?Ç¥?ö©';
COMMENT ON COLUMN BOARD.PROD_IMG IS '?ÉÅ?íà ?ù¥ÎØ∏Ï?';
COMMENT ON COLUMN BOARD.PRICE IS '?ÉÅ?íà Í∞?Í≤?(Ï¶âÏãú ?ÇôÏ∞∞Í?)';
COMMENT ON COLUMN BOARD.BID_PRICE IS 'Í≤ΩÎß§ Í∞?Í≤?(?òÑ?û¨ ?ûÖÏ∞∞Í?)';
COMMENT ON COLUMN BOARD.STOCK IS '?ÉÅ?íà ?àò?üâ';
COMMENT ON COLUMN BOARD.SELLER_NO IS '?åêÎß§Ïûê Î≤àÌò∏';
COMMENT ON COLUMN BOARD.REGISTER_DATE IS '?åêÎß§Îì±Î°ùÏùº';
COMMENT ON COLUMN BOARD.STATUS IS '?åêÎß? ?ÉÅ?Éú(Y/N)';

CREATE SEQUENCE SEQ_BNO
NOCACHE;

/* Address */
CREATE TABLE ADDRESS (
    USER_NO NUMBER ,
    ADDRESS_NAME    VARCHAR2(30)    NOT NULL    UNIQUE,
    RECEIVER    VARCHAR2(30)    NOT NULL,
    DELIVERY_ADDRESS    VARCHAR2(300)   NOT NULL,
    POST_CODE   NUMBER  NOT NULL,
    PHONE   VARCHAR2(13)   NOT NULL
);

COMMENT ON COLUMN ADDRESS.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN ADDRESS.ADDRESS_NAME IS 'Î∞∞ÏÜ°Ïß? ?ù¥Î¶?';
COMMENT ON COLUMN ADDRESS.RECEIVER IS 'Î∞õÎäî?ù¥';
COMMENT ON COLUMN ADDRESS.DELIVERY_ADDRESS IS 'Î∞∞ÏÜ°Ï£ºÏÜå';
COMMENT ON COLUMN ADDRESS.POST_CODE IS '?ö∞?é∏Î≤àÌò∏';
COMMENT ON COLUMN ADDRESS.PHONE IS '?†Ñ?ôîÎ≤àÌò∏';

COMMIT;